export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  CART_PRODUCT: "CART_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_CART_ITEMS: 'SET_CART_ITEMS',
  SET_SHIPPING_ADDRESS: 'SET_SHIPPING_ADDRESS',
  SET_SHIPPING_METHOD: 'SET_SHIPPING_METHOD',
  SET_PAYMENT_METHOD: 'SET_PAYMENT_METHOD',
  SET_WISHLIST:'SET_WISHLIST'
};
